### ISSUE TITLE
`data.dta` yields `DataFrame` with `Float32`

### ISSUE THREAD

**Issue by greimel** [queryverse/StatFiles.jl#18]
Is there a way to automatically change the type of all float variables to `Float64`?

Due to a bug, one cannot fit linear models with `Float32` in `GLM.jl`?

see JuliaStats/GLM.jl#260

**Comment by davidanthoff** [comment]
There are probably multiple ways you could do that e.g. in a `DataFrame`. I think doing anything about this here in this package is probably out of scope: we just return the data type that is used in the file.

**Comment by tyleransom** [comment]
For anyone else coming across this, I encountered this exact problem and solved this with the following function (inspired by [this thread](https://discourse.julialang.org/t/how-to-change-field-names-and-types-of-a-dataframe/43991/11) on Discourse):

```julia
# fix types in data
function make_types_64!(df)
    for c in names(df)
        if eltype(df[!,c])==Float32
            df[!,c] = convert.(Float64,df[!,c])
        elseif eltype(df[!,c])==Int8
            df[!,c] = convert.(Int64,df[!,c])
        end
    end
    return df
end
make_types_64!(df)
```
